config/routes.rb
Rails.application.routes.draw do

   devise_for :users
  root to: "homes#top"
  get 'home/about' => "homes#about"
  #ネストさせる
  resources :books do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  #ネストさせる
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
     get "search" => "searches#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true

  validates :body, presence: true, length: { maximum: 200 }

    def favorited_by?(user)
      favorites.exists?(user_id: user.id)
    end
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :books, dependent: :destroy
 has_many :book_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy

 #フォローしている人の取得
 has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
 #フォローされている人の取得
 has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
 #自分がフォローしている人
 has_many :followings, through: :relationships, source: :followed
 #自分をフォローしてくれている人
 has_many :followers, through: :reverse_of_relationships, source: :follower

 has_one_attached :profile_image

 validates :name, uniqueness: true, length: {minimum: 2, maximum: 20 }
 validates :introduction, length: { maximum: 50 }

    def get_profile_image
      (profile_image.attached?) ? profile_image : 'no_image.jpg'
    end

    #フォローした時の処理
    def follow(user)
      relationships.create(followed_id: user.id)
    end

    #フォロー外す時の処理
    def unfollow(user)
      relationships.find_by(followed_id: user.id).destroy
    end

    #フォローしているかを判定
    def following?(user)
      followings.include?(user)
    end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?

 def after_sign_in_path_for(resource)
    user_path(current_user)
 end

 def after_sign_out_path_for(resource)
    root_path
 end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    if comment.save
       redirect_to book_path(book)
    else
       render :'books/show' 
    end
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end


  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :authenticate_user!


  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.page(params[:page])
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
   if @book.destroy
      flash[:notice] = "Book was successfully destroyed." # データ（レコード）を削除
      redirect_to books_path  #投稿一覧画面へリダイレクト
   end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to book_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to book_path(book)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search],params[:word])
    else
      @books = Book.looks(params[:search],params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page])
    @book = Book.new
  end

  def index
    @book = Book.new
    @user = current_user
    @users = User.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
     @user = User.find(params[:id])
     @books = Book.all
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_form.html.erb
<%= form_with model: [@book, @book_comment] do |f| %>
  <%= f.text_area :comment, rows: '5', cols: '85'  %><br>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/_index.html.erb
<table>
    <tbody>
      <% @book.book_comments.each do |book_comment| %>
      <tr>
    　   <td>
    　     <%= link_to user_path(book_comment.user) do %>
    　     <%= image_tag book_comment.user.get_profile_image, size:'50×50' %><br>
          <%= book_comment.user.name %>
          <% end %>
        </td>
        <td><%= book_comment.comment %></td>
        <td>
          <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger destroy_book_#{@book.id}" %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/books/_form.html.erb
<%= form_with model:@book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag @user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %>
        </td>
        <td><%= render "favorites/btn", book: book %></td>
        <td>
           <p>コメント数：<%= book.book_comments.count %></p>
        </td>
      </tr>
    <% end %>
    <%= paginate books %>
  </tbody>
</table>

app/views/books/edit.html.erb
<%= form_with model:@book, local:true do |f| %>
<%= render 'layouts/errors', obj: @book %>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 com-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'books/form', book: @book %>
      <%= link_to 'show', @book, class: "book_#{@book.id}" %>
      <%= link_to 'Back', books_path, class: "back" %>
    </div>
  </div>
</div>
<% end %>

app/views/books/index.html.erb
<%= form_with model:@book, local:true do |f| %>
<%= render 'layouts/errors', obj: @book %>
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <h2>User info</h2>
   <%= render 'users/info', user: current_user %>
   <h2 class="mt-3">New book</h2>
   <%= render 'form', book: @book %>
  </div>
  <div class='col-md-8 offset-md-1'>
   <%= render 'searches/search' %>
   <h2>Books</h2>
   <%= render 'index', books: @books %>
  </div>
 </div>
</div>
<% end %>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model:Book.new,local:true do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <%= f.label :opinion %>
        <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"50x50" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td>コメント数：<%= @book.book_comments.count %></td>
          <td><%= render "favorites/btn", book:@book %></td>
             <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
            <% end %>
        </tr>
      </table>
        <%= render "book_comments/index", book:@book %>
        <%= render "book_comments/form", book:@book, book_comment:@book_comment %>
    </div>
  </div>
</div>

app/views/favorites/_btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
    ♥<%= book.favorites.count %> いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
    ♡<%= book.favorites.count %> いいね
  <% end %>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image, size:'50×50' %></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.followings.count%></td>
      <td>フォロワー数：<%= user.followers.count%></td>
      <td><%= render "relationships/following", user: user %></td>
      <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
    </tr>
    <% end %>
    <%= paginate users %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'50×50' %></tr>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user)%></th>
  </tr>
</table>

<div class='row'>
  <% if user.id == current_user.id %>
    <td><%= render 'relationships/following', user: user %></td>
  <% else %>
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= form_with model:@user, local:true do |f| %>
<%= render 'layouts/errors', obj: @user %>
<div class='container'>
 <div class='row'>
  <div class="col-sm-12 col-lg-5 px-5 px-sm-0 mx-auto">
   <h2>User info</h2>
   <div class="form-group">
    <%= f.label :mame %>
    <%= f.text_field :name, class: "form-control name" %>
   </div>
   <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
   </div>
   <div class="form-group">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "form-control introduction" %>
   </div>
   <div class="form-group">
    <%= f.submit class: 'btn btn-secondary' %>
   </div>
   <% end %>
  </div>
 </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <h2>User info</h2>
   <%= render 'info', user: current_user %>
   <h2 class="mt-3">New book</h2>
   <%= render 'books/form', book: @book %>
  </div>
  <div class='col-md-8 offset-md-1'>
   <h2>Users</h2>
   <%= render 'index', users: @users %>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class='col-md-3'>
   <h2>User info</h2>
   <%= render 'info', user: @user %>
   <h2 class="mt-3">New book</h2>
   <%= render 'books/form', book: @book %>
  </div>
  <div class='col-md-8 offset-md-1'>
   <h2>Books</h2>
   <%= render 'books/index',books: @books %>
  </div>
 </div>
</div>